# ============================================================
# SEED 原始 EEG - 格式 (62通道, 200时间点)
# seq_length = 62, feature_size = 200
# ============================================================

model:
  target: Models.interpretable_diffusion.FMTS.FM_TS
  params:
    seq_length: 62          # 62 个 EEG 通道
    feature_size: 200       # 200 个时间点
    n_layer_enc: 4
    n_layer_dec: 6
    d_model: 128
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.1
    kernel_size: 5
    padding_size: 2

solver:
  base_lr: 5.0e-5
  max_epochs: 10000
  gradient_accumulate_every: 1
  save_cycle: 1000
  ema:
    decay: 0.995
    update_interval: 10

dataloader:
  train_dataset:
    target: Utils.Data_utils.seed_dataset.SEEDDataset
    params:
      name: SEED_RAW
      data_root: /root/autodl-tmp/Preprocessed_EEG
      data_type: raw
      window: 200
      stride: 100
      proportion: 0.8
      neg_one_to_one: True
      scaler_type: minmax
      seed: 42
      period: train
      conditional: True

  batch_size: 128
  shuffle: True